on: [push, pull_request]

jobs:
  conan_latest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Conan Stable - Python 2.7", python: 2.7, toxenv: "py27-conan-latest", pyver: "py27" }
          - { name: "Conan Stable - Python 3.7", python: 3.7, toxenv: "py37-conan-latest", pyver: "py37" }
          - { name: "Conan Develop - Python 2.7", python: 2.7, toxenv: "py27-conan-dev", pyver: "py27" }
          - { name: "Conan Develop - Python 3.7", python: 3.7, toxenv: "py37-conan-dev", pyver: "py37" }
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.python }}
    - name: Install dependencies
      run: |
        chmod +x .ci/travis/install.sh
        .ci/travis/install.sh
    - name: ${{ matrix.config.name }}
      env:
        TOXENV: ${{ matrix.config.toxenv }}
        PYVER: ${{ matrix.config.pyver }}
      run: |
        chmod +x .ci/travis/run.sh
        .ci/travis/run.sh
    - name: Codecov
      run: |
        bash <(curl -s https://codecov.io/bash)
